/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_crs4_most_visualization_augmentedreality_OpticalARToolkit */

#ifndef _Included_it_crs4_most_visualization_augmentedreality_OpticalARToolkit
#define _Included_it_crs4_most_visualization_augmentedreality_OpticalARToolkit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_crs4_most_visualization_augmentedreality_OpticalARToolkit
 * Method:    getOpticalMatrices
 * Signature: (Ljava/lang/String;Ljava/lang/String;[F[F[F[FF)I
 */
JNIEXPORT jint JNICALL Java_it_crs4_most_visualization_augmentedreality_OpticalARToolkit_getOpticalMatrices
  (JNIEnv *, jobject, jstring, jstring, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
